baseURL = "https://samt-bu-docs.pages.dev/"
title = "SAMT-BU Docs"
theme = "hugo-theme-samt-bu"
defaultContentLanguage = "nb"
defaultContentLanguageInSubdir = false
enableGitInfo = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.nb]
    languageCode = "nb-NO"
    languageName = "Bokmål"
    title = "SAMT-BU Docs"
    weight = 1
    [languages.nb.params]
      navSwitcherLabel = "Innhold"
      navSwitcherPlaceholder = "Velg seksjon"
  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    title = "SAMT-BU Docs"
    weight = 2
    [languages.en.params]
      navSwitcherLabel = "Content"
      navSwitcherPlaceholder = "Select section"

[markup.goldmark.renderer]
  unsafe = true

[params]
  editURL = "https://github.com/SAMT-X/samt-bu-docs/edit/main/content/"

[[params.navSwitcher]]
  id = "om"
  title = "Om SAMT-BU"
  url = "om/"
  icon = "fa-info-circle"

[[params.navSwitcher]]
  id = "behov"
  title = "Behov"
  url = "behov/"
  icon = "fa-lightbulb-o"

[[params.navSwitcher]]
  id = "pilotering"
  title = "Piloter"
  url = "pilotering/"
  icon = "fa-flask"

[[params.navSwitcher]]
  id = "arkitektur"
  title = "Arkitektur"
  url = "arkitektur/"
  icon = "fa-sitemap"

[[params.navSwitcher]]
  id = "loesninger"
  title = "Løsninger"
  url = "loesninger/"
  icon = "fa-cogs"

[[params.navSwitcher]]
  id = "rammeverk"
  title = "Rammeverk"
  url = "rammeverk/"
  icon = "fa-cubes"


[[params.navSwitcher]]
  id = "innsikt"
  title = "Felles innsikt"
  url = "innsikt/"
  icon = "fa-bar-chart"


[[params.navSwitcher]]
  id = "utkast"
  title = "Utkast og innspill"
  url = "utkast/"
  icon = "fa-pencil"

[module]
  [[module.imports]]
    path = "github.com/SAMT-X/team-architecture"
    [[module.imports.mounts]]
      source = "content"
      target = "content/arkitektur/overordnet-arkitektur"

  [[module.imports]]
    path = "github.com/SAMT-X/samt-bu-drafts"
    [[module.imports.mounts]]
      source = "content"
      target = "content/utkast"


  [[module.imports]]
    path = "github.com/SAMT-X/team-semantics"
    [[module.imports.mounts]]
      source = "content"
      target = "content/pilotering/pilot-1/informasjonsarkitektur"

  [[module.imports]]
    path = "github.com/SAMT-X/team-pilot-1"
    [[module.imports.mounts]]
      source = "content"
      target = "content/pilotering/pilot-1"

  [[module.imports]]
    path = "github.com/SAMT-X/solution-samt-bu-docs"
    [[module.imports.mounts]]
      source = "content"
      target = "content/loesninger/cms-loesninger/samt-bu-docs"
